---
project_name: kandalf

builds:
  - id: binary-build
    main: main.go
    binary: kandalf
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "hellofresh/kandalf:latest"
      - "hellofresh/kandalf:{{.Tag}}"
    dockerfile: Dockerfile
    extra_files:
      - assets/pipes.yml
